import Vue from "vue";
import {
    Button,
    Tabbar,
    TabbarItem,
    Search,
    Swipe,
    SwipeItem,
    Image as VanImage,
    Grid,
    GridItem,
    NavBar,
    Sidebar,
    SidebarItem,
    Tab,
    Tabs,
    Lazyload,
    Loading,
    Toast,
    GoodsAction,
    GoodsActionIcon,
    GoodsActionButton,
    Badge,
    SwipeCell,
    Cell,
    CellGroup,
    Checkbox,
    CheckboxGroup,
    Stepper,
    SubmitBar,
    Dialog,
    Icon,
    Col,
    Row,
    Form,
    Field,
    RadioGroup,
    Radio,
    DatetimePicker,
    Popup,
} from "vant";

Vue.use(Button)
    .use(Tabbar)
    .use(TabbarItem)
    .use(Search)
    .use(Swipe)
    .use(SwipeItem)
    .use(VanImage)
    .use(Grid)
    .use(GridItem)
    .use(NavBar)
    .use(Sidebar)
    .use(SidebarItem)
    .use(Tab)
    .use(Tabs)
    .use(Lazyload)
    .use(Loading)
    .use(Toast)
    .use(GoodsAction)
    .use(GoodsActionIcon)
    .use(GoodsActionButton)
    .use(Badge)
    .use(SwipeCell)
    .use(Cell)
    .use(CellGroup)
    .use(Checkbox)
    .use(CheckboxGroup)
    .use(Stepper)
    .use(SubmitBar)
    .use(Dialog)
    .use(Icon)
    .use(Col)
    .use(Row)
    .use(Form)
    .use(Field)
    .use(RadioGroup)
    .use(Radio)
    .use(Popup)
    .use(DatetimePicker);